packages/PythonScripts/scripts/PythonLibs

Additional functionality to display python libraries available in the current env

Created PythonLibs

---

help/stories/life-sciences.md

I've noticed a couple of truncated sentences in this text and decided to proofread it. Please consider these edits :hugs:

life-sciences.md

---

packages/Sunburst/src/sunburst-renderer.ts
packages/Sunburst/src/sunburst-viewer.ts
packages/Sunburst/src/tree-data-builder.ts

This helps reduce memory usage by utilizing datagrok internals for aggregation.

Sunburst: Group-by/JoinTables as data source

---

packages/Chem/src/chem_searches.js
packages/Chem/src/rdkit_substruct_library.js

- do not add molecules twice to substructure library
- no need to overwrite cells if SMILES

Molecules should not be added twice to substructure library and a small optimization

---

libraries/utils/package.json
libraries/utils/src/operations.ts
libraries/utils/src/reduce_dimensionality.ts
libraries/utils/src/spe.ts
libraries/utils/src/string_measure.ts
libraries/utils/src/type_declarations.ts

1. String measures: 
- Levenshtein,
- Jaro-Winkler.
2. Dimensionality reduction methods:
- UMAP,
- t-SNE,
- SPE,
- PSPE.
3. Some linear algebra operations (based on [vectorious](https://github.com/mateogianolio/vectorious)).

Add utils used in Peptides package.

---

libraries/utils/src/reduce-dimensionality.ts
libraries/utils/src/sequence-encoder.ts
packages/Peptides/src/utils/peptide-similarity-space.ts

#93 
1. Added trick with distance callback wrapping to cast distanceFn.
2. Added aligned sequence cleaning to drop auxiliary dashes.

Utils: UMAP fixes.

---

help/visualize/viewers/correlation-plot.md
js-api/src/views/view.ts

Added link to the Spearman's correlation coefficient which can also be selected by an user.

Documentation: Correlation plot can also show Spearman's correlation.

---

packages/PowerGrid/.eslintrc.json
packages/PowerGrid/package-lock.json
packages/PowerGrid/package.json
packages/PowerGrid/setup.cmd
packages/PowerGrid/src/cell-types/bar-cell-renderer.ts
packages/PowerGrid/src/cell-types/binary-image-cell-renderer.ts
packages/PowerGrid/src/cell-types/hyperlink-cell-renderer.ts
packages/PowerGrid/src/cell-types/image-cell-renderer.ts
packages/PowerGrid/src/cell-types/test-cell-renderer.ts
packages/PowerGrid/src/package.ts
packages/PowerGrid/src/sparklines/barchart.ts
packages/PowerGrid/src/sparklines/base.ts
packages/PowerGrid/src/sparklines/piechart.ts
packages/PowerGrid/src/sparklines/radarchart.ts
packages/PowerGrid/src/sparklines/shared.ts
packages/PowerGrid/src/sparklines/sparklines-lines.ts

TypeScript custom cell renderers using Rect and Canvas additional methods in js-api
+eslint rules

Closes #491: Make typescript renderers for PowerGrid package

---

libraries/bio/src/viewers/web-logo.ts

Fix for JsViewer.isDetached attribute

Fix bio WebLogo startPosition endPosition options and positionNames tag

---

libraries/bio/src/viewers/web-logo.ts

Fix for JsViewer.dataFrame attribute

Fix bio WebLogo startPosition endPosition options and positionNames

---

packages/PowerGrid/src/sparklines/barchart.ts
packages/PowerGrid/src/sparklines/piechart.ts
packages/PowerGrid/src/sparklines/radarchart.ts
packages/PowerGrid/src/sparklines/sparklines-lines.ts

Custom cell renderers for summary columns. Fix.

---

packages/ApiTests/src/dataframe/dataframe.ts

JS API Tests: DataFrame: test each exposed method and property

GROK-10717

---

packages/Chem/src/analysis/r-group-analysis.ts
packages/Chem/src/package.ts
packages/Chem/src/rdkit-service/rdkit-service-worker-substructure.ts
packages/Chem/src/rendering/rdkit-cell-renderer.ts
packages/Chem/src/utils/chem-common-rdkit.ts
packages/Chem/src/widgets/scaffold-tree.ts

Reverts datagrok-ai/public#1575

Revert "dpetrov/1566 generic support for molecules fialed to kekulize"

---

help/datagrok/functions/func-params-annotation.md

Create the main article about parameter annotations (the most detailed description is in scripting.md) and link it with articles on various function types (scripts, queries, etc.)
---
Once the draft is accepted, the repetitive sections in other articles will be replaced with a link to the main article.

Wiki: GROK-12341: Functions: Parameter annotations

---

packages/Meta/package.json

Remove MolecularLiabilityBrowser from the public repository

GROK-12619: MLB: Remove MLB from public

---

packages/Bio/package.json
packages/Bio/src/tests/pepsea-tests.ts
packages/Bio/src/tests/renderers-test.ts
packages/Bio/src/tests/splitters-test.ts

Skip failed tests to allow update package to npm

GROK-12136: Bio | Tools: Stability and polishing

---

packages/BiostructureViewer/src/apps/biostructure-app.ts
packages/BiostructureViewer/src/package.ts
packages/BiostructureViewer/src/viewers/molstar-viewer.ts
packages/BiostructureViewer/src/viewers/ngl-aspect.ts
packages/BiostructureViewer/src/viewers/ngl-ui.ts
packages/BiostructureViewer/src/viewers/view-preview.ts

BiostructureViewer package
File handler opening PDB with molstar viewer
without data frame with residues
Shared files preview PDB with molstar viewer

GROK-12136: Bio: Stability and polishing

---

libraries/bio/package.json

Change bio lib ownership to atanas

GROK-12136: Bio | Tools: bio lib ownership

---

packages/Bio/package-lock.json
packages/Bio/package.json
packages/Bio/src/package.ts

GROK-12797: Bio | Tools: Demo fix names

---

libraries/compute-utils/function-views/src/function-view.ts
libraries/compute-utils/function-views/src/rich-function-view.ts
libraries/compute-utils/function-views/src/shared/consts.ts
libraries/compute-utils/function-views/src/shared/utils.ts
libraries/compute-utils/history-utils/src/history-utils.ts
packages/Compute/scripts/default-immediate.js

Provide `meta.isImmediate` tag to enable this feature in RFV

ComputeUtils: Added immediate functions support to RFV

---

packages/Bio/package.json
packages/Bio/src/demo/bio01-similarity-diversity.ts
packages/Bio/src/demo/bio01a-hierarchical-clustering-and-sequence-space.ts
packages/Bio/src/demo/bio01b-hierarchical-clustering-and-activity-cliffs.ts
packages/Bio/src/demo/bio05-helm-msa-sequence-space.ts
packages/Bio/src/demo/utils.ts
packages/Bio/src/package.ts

GROK-13019: Bio | Demos: Fixes tier 1

---

libraries/bio/package.json
libraries/bio/src/viewers/ngl-gl-viewer.ts

Move RepresentationType to bio lib
Add const NglPropsDefault, type NglProps, interface INglViewer

GROK-13019: Bio | Demo: Fixes tier 1a

---

packages/Bioreactors/package.json
packages/Bioreactors/src/package.ts
packages/EDA/package.json
packages/EDA/src/package.ts

GROK-13014: EDA: Demo

---

packages/BiostructureViewer/.eslintrc.json
packages/BiostructureViewer/detectors.js
packages/BiostructureViewer/package.json
packages/BiostructureViewer/src/package.ts
packages/BiostructureViewer/src/viewers/molstar-viewer.ts
packages/BiostructureViewer/src/viewers/ngl-viewer.ts

Add condition on this.viewed  for rebuildViewLigands

GROK-12136: Bio | Tools: Fix NGL viewer test

---

packages/Bioreactors/package.json
packages/Bioreactors/src/package.ts

Basic version of Bioreactor demo application

GROK-12996: Bioreactors : Demo app

---

packages/BiostructureViewer/detectors.js

Fix detectors.js onContextMenu handler

GROK-12136: Bio | Tools: BiostructureViewer fix onContextMenu

---

libraries/bio/package.json
libraries/bio/src/trees/tree-helper.ts

bio lib fix TreeHelper message

GROK-12136: Bio | Tools: bio lib fix TreeHelper message

---

packages/Bioreactors/src/package.ts
packages/Bioreactors/wasm/helpPanel.js
packages/EDA/src/package.ts

Minor UI updates in Bioreactor and MVA demo apps

GROK-12996: Bioreactors | Demo app: UI updates

---

packages/Bio/package.json
packages/Bio/src/package.ts
packages/Bio/src/tests/converters-test.ts
packages/Bio/src/tests/to-atomic-level-tests.ts

Fix toAtomicLevel to use Monomer Library
Add tests for toAtomicLevel
Fix tests for converters
Fix atomicCliffs

GROK-13093: Bio | Demo: Fix toAtomicLevel to use Monomer Library

---

packages/EDA/src/package.ts

Dialog window is moved - minor UI fix

GROK-13014: EDA | Demo: UI update

---

packages/Bio/package.json
packages/Bio/src/demo/bio01a-hierarchical-clustering-and-sequence-space.ts
packages/BiostructureViewer/package.json
packages/BiostructureViewer/src/demo/bio06-docking-ngl.ts
packages/BiostructureViewer/src/demo/bio07-molecule3d-in-grid.ts
packages/BiostructureViewer/src/package.ts

Fix demo names, function description, bump version

GROK-12972: Chem | Demo: Fixes for Demo

---

packages/BiostructureViewer/package.json
packages/BiostructureViewer/src/tests/molstar-preview-tests.ts
packages/BiostructureViewer/src/typings/index.d.ts
packages/BiostructureViewer/src/utils/ngl-gl-doc-service.ts
packages/BiostructureViewer/src/utils/ngl-gl-service.ts

Repair for the new platform version

GROK-12136: Bio | Tools: Fix Molecule3D cell renderer

---

packages/Bio/package.json
packages/Bio/src/package.ts

Disable Representations widget panel for Macromolecule semantic type cells

GROK-13019: Bio | Demo: Fixes tier 2a

---

packages/Bioreactors/package.json
packages/EDA/package.json

In package.json file, version update.

GROK-13014: EDA | Demo: Minor fixes

---

packages/BiostructureViewer/package.json
packages/BiostructureViewer/src/package.ts

BiostructureViewer enable demo Proteins

GROK-13019: Bio | Demo: Fixes tier 2c

---

libraries/bio/package.json
libraries/bio/src/viewers/molstar-viewer.ts

Add type MolstarDataType with ext for format

GROK-13131: Bio | Tools: BiostructureViewer support formats

---

libraries/ml/package.json
libraries/ml/src/reduce-dimensionality.ts
libraries/ml/src/viewers/activity-cliffs.ts

Umap reduction method was not returning the distance matrix. because of this, we had to calculate matrix again for activity cliffs. this led to calculation time almost doubling

GROK-13140: ML: Return distance matrix from umap

---

packages/Chem/files/alert-collection.csv
packages/Chem/src/package.ts
packages/Chem/src/panels/structural-alerts.ts
packages/Chem/src/rdkit-service/rdkit-service-worker-api.ts
packages/Chem/src/rdkit-service/rdkit-service-worker-client.ts
packages/Chem/src/rdkit-service/rdkit-service-worker-substructure.ts
packages/Chem/src/rdkit-service/rdkit-service.ts
packages/Chem/src/rdkit.worker.ts
packages/Chem/src/tests/screening-tools.ts

Fixed and parallelized structural alerts detection

GROK-12077: Structural alerts fix

---

help/develop/advanced/data-frame.md
libraries/bio/package.json
libraries/bio/src/types/index.ts

Add IMonomerLib.error property allowing to mark invalid monomer libraries.

GROK-12136: Bio | Tools: Fix tests for new release lib

---

help/develop/advanced/data-frame.md
packages/Bio/src/package.ts

Fix UI for Manage Libraries panel of Helm column

GROK-13249: Bio | Tools: Fix monomer libraries settings

---

packages/Helm/package.json
packages/Helm/src/cell-renderer.ts

Bump version for new bio lib changes IMonomerLib

GROK-13243: Bio | Tools: Optimize WebLogo, Helm

---

libraries/bio/package-lock.json
libraries/bio/package.json
libraries/bio/src/monomer-works/to-atomic-level.ts
libraries/bio/src/utils/fasta-handler.ts
libraries/bio/src/utils/macromolecule/index.ts
libraries/bio/src/utils/macromolecule/utils.ts
libraries/bio/src/utils/notation-converter.ts
libraries/bio/src/utils/units-handler.ts

Cache UnitsHandler within column's temp slot
Use UnitsHandler.getOrCreate(col) instead of constructor Cache splitted within UnitsHandler
Cache stats within UnitsHandler
Bump bio lib version

GROK-13243: Bio | Tools: Optimize WebLogo, bio lib

---

packages/Bio/files/data/sample_HELM_empty_vals.csv
packages/Bio/files/samples/sample_HELM.csv
packages/Bio/package.json

Fix sample data adding square brackets to monomers with parentheses

GROK-13355: Bio | Tools: Fix Helm renderer for gaps, Bio

---

packages/Helm/package.json
packages/Helm/src/cell-renderer.ts

Fix Helm cell renderer skipping gaps stars

GROK-13355: Bio | Tools: Fix Helm renderer for gaps, Helm

---

packages/Bio/package.json
packages/Bio/scripts/sequence_generator.py
packages/Bio/src/package.ts
packages/Bio/src/tests/WebLogo-positions-test.ts
packages/Bio/src/viewers/web-logo-viewer.ts

Encapsulate working with monomer frequencies into PositionInfo 
Add recalc levels for rendering requests None, Layout, Freqs 
Arrange WebLogo life cycle with postponed render
Optimize countForMonomerAtPosition

GROK-13243: Bio | Tools: Optimize WebLogo 2, Bio

---

libraries/bio/package-lock.json
libraries/bio/package.json
libraries/bio/src/utils/units-handler.ts

Add column type check in UnitsHandler

GROK-13243: Bio | Tools : Optimize WebLogo, fix bio lib

---

packages/Bio/detectors.js
packages/Bio/package.json
packages/Bio/src/tests/detectors-benchmark-tests.ts

Fix detectMacromolecule to avoid the use of categories 
Remove skipReason marks for detectMacromolecule benchmark tests

GROK-12136: Bio : Stability and polishing

---

libraries/bio/package.json
libraries/bio/src/viewers/web-logo.ts

WebLogo positionLabels tag, tooltipWebLogo tag, onSizeChanged event

GROK-13473: Bio | Tools: WebLogo positionLabels, bio lib

---

packages/Bio/detectors.js
packages/Bio/package.json
packages/Bio/src/tests/WebLogo-positions-test.ts
packages/Bio/src/tests/detectors-tests.ts
packages/Bio/src/tests/msa-tests.ts
packages/Bio/src/tests/renderers-test.ts
packages/Bio/src/tests/splitters-test.ts
packages/Bio/src/tests/utils/sequences-generators.ts
packages/Bio/src/utils/convert.ts
packages/Bio/src/viewers/web-logo-viewer.ts

Use monomer length variance heuristics to detectMacromolecule with separator units. Uncover skipped tests of Bio
Fix WebLogo for WebLogo-positions tests

GROK-13486: Bio | Tools: Add heuristics to detectMacromolecule

---

packages/Bio/package.json
packages/Bio/src/package-types.ts
packages/Bio/src/package.ts
packages/Bio/src/utils/macromolecule-column-widget.ts
packages/Bio/src/utils/monomer-lib.ts
packages/Bio/src/viewers/web-logo-viewer.ts
packages/Bio/src/widgets/package-settings-editor-widget.ts

Add Bio package settings TooltipWebLogo
Macromolecule column tooltip WebLogo controls 
by package settings tooltipWebLogo and column's tag .tooltipWebLogo 
Fix positionWidth to respect devicePixelRatio

GROK-13471: Bio | Tools: Control WebLogo in tooltips

---

packages/Chem/src/rdkit_lib_version.js

Address RDKit issue [#6523](https://github.com/rdkit/rdkit/issues/6523) by reverting RDKit PR #6473.
@MariaDolotova @StLeonidas Please update DG to this MinimalLib version.

update MinimalLib to 1.2.9 (reverts RDKit PR #6473)

---

packages/Helm/package.json
packages/Helm/src/cell-renderer.ts
packages/Helm/src/constants.ts
packages/Helm/src/package-test.ts
packages/Helm/src/tests/renderers-tests.ts

Fix missed file renderers-tests.ts

GROK-12163: Bio: Helm cell renderer onMouseMove error

---

packages/Bio/package.json
packages/Bio/src/substructure-search/substructure-search.ts
packages/Bio/tsconfig.json
packages/Bio/webpack.config.js

Fix substructure search on Helm (Macromolecule)

GROK-13354: Bio: Substructure search does not work on Helm, Bio

---

packages/Bio/package.json
packages/Bio/src/package.ts

GROK-13354: Bio | Tools: Rearrange top menu, Bio

---

libraries/bio/CHANGELOG.md
libraries/bio/package-lock.json
libraries/bio/package.json
libraries/bio/src/utils/macromolecule/consts.ts
libraries/bio/src/utils/notation-converter.ts
libraries/bio/src/utils/units-handler.ts

Add NotationConverter.getConverter() returning a function to convert a single value

GROK-13435: Bio: Add Copy items to macromolecule cell context menu bio lib

---

packages/Bio/CHANGELOG.md
packages/Bio/detectors.js
packages/Bio/package.json
packages/Bio/src/package-types.ts
packages/Bio/src/package.ts
packages/Bio/src/tests/converters-test.ts
packages/Bio/src/utils/cell-renderer.ts
packages/Bio/src/utils/context-menu.ts
packages/Bio/src/utils/convert.ts
packages/Bio/src/utils/macromolecule-column-widget.ts
packages/Bio/src/viewers/vd-regions-viewer.ts
packages/Bio/src/widgets/package-settings-editor-widget.ts
packages/Bio/src/widgets/representations.ts

Add Copy group to Macromolecule cell context menu
Add DefaultSeparator package property settings
Fix VdRegionsViewer filter source checkbox tooltip workaround

GROK-13435: Bio: Add Copy items to Macromolecule cell context menu, Bio

---

libraries/bio/CHANGELOG.md
libraries/bio/package-lock.json
libraries/bio/package.json
libraries/bio/src/utils/macromolecule/utils.ts

Fix monomerToShort to get a string not longer than maxLengthOfMonomer

GROK-13659: Bio | tools: Fix max monomer length macromolecule cell renderer bio lib

---

packages/EDA/CHANGELOG.md
packages/EDA/package.json
packages/EDA/src/package.ts

PLS is moved to Top Menu | ML and minor fixes are introduced

GROK-13691: EDA: Replace PLS to ML

---

libraries/bio/.eslintrc.json
libraries/bio/CHANGELOG.md
libraries/bio/package-lock.json
libraries/bio/package.json
libraries/bio/src/monomer-works/monomer-utils.ts
libraries/bio/src/monomer-works/to-atomic-level.ts
libraries/bio/src/utils/cell-renderer-monomer-placer.ts
libraries/bio/src/utils/cell-renderer.ts
libraries/bio/src/utils/macromolecule/consts.ts
libraries/bio/src/utils/macromolecule/index.ts
libraries/bio/src/utils/macromolecule/types.ts
libraries/bio/src/utils/macromolecule/utils.ts
libraries/bio/src/utils/notation-converter.ts
libraries/bio/src/utils/splitter.ts
libraries/bio/src/utils/units-handler.ts

SplitterFunc now returns ISeqSplitted
allowing optimization for single character alphabets

GROK-13708: Bio | WebLogo: Optimize with splitterAsFastaSimple, bio lib

---

js-api/src/dataframe.ts

Fixed description of length in ColumnList

GROK-13720: JS-API: Fix method description

---

libraries/bio/CHANGELOG.md
libraries/bio/package-lock.json
libraries/bio/package.json
libraries/bio/src/utils/cell-renderer.ts
libraries/bio/src/utils/units-handler.ts
libraries/bio/src/viewers/vd-regions.ts
libraries/bio/src/viewers/web-logo.ts

Move maxMonomerLength from column's temp to tags
Add property fitWidth for VdRegionsViewer
Fix VdRegionsViewer fit width accounting position margin of WebLogo
Fix UnitsHandler to not replace existing tags

GROK-13472: Bio: VdRegionsViewer fit width

---

packages/Bioreactors/CHANGELOG.md
packages/Bioreactors/package.json
packages/Bioreactors/src/package.ts

Line chart legend bug is fixed.

GROK-11775: Bioreactors: Fix legend

---

packages/Bioreactors/CHANGELOG.md
packages/Bioreactors/package.json
packages/Bioreactors/src/package.ts

Demo is moved to the Compute section & the runOnOpen feature is added.

GROK-14085: Bioreactor: Demo update

---

help/explore/anova.md

ANOVA help is updated with respect to the corresponding EDA feature update (move to Top-menu | Analyze | ...)

GROK-14125: Help | Anova: Naming update

---

packages/Tutorials/CHANGELOG.md
packages/Tutorials/package.json

MVA tutorial is fixed (version is updated).

GROK-14126: Tutorials: MVA fix

---

packages/Bio/CHANGELOG.md
packages/Bio/package.json
packages/Bio/src/apps/web-logo-app.ts
packages/Bio/src/package.ts
packages/Bio/src/tests/WebLogo-positions-test.ts
packages/Bio/src/utils/agg.ts
packages/Bio/src/viewers/web-logo-viewer.ts
packages/Bio/src/widgets/composition-analysis-widget.ts
packages/Bio/webpack.config.js

Add WebLogo aggregation function
Add WebLogo position tooltip with composition table (for count)

GROK-14127: Bio: WebLogo with aggregation function

---

packages/EDA/CHANGELOG.md
packages/EDA/package-lock.json
packages/EDA/package.json
packages/EDA/src/package.ts

Methods descriptions update are updated.

GROK-14176: EDA: Methods descriptions update

---

packages/SimPKPD/CHANGELOG.md
packages/SimPKPD/README.md
packages/SimPKPD/package-lock.json
packages/SimPKPD/package.json
packages/SimPKPD/src/package.ts
packages/SimPKPD/wasm/help-panel.js

Tooltips & decriptions are updated

GROK-14237: SimPKPD: Minor fixes

---

libraries/bio/CHANGELOG.md
libraries/bio/package.json
libraries/bio/src/molecule-3d/index.ts
libraries/bio/src/molecule-3d/molecule-3d-build-data.ts
libraries/bio/src/molecule-3d/molecule-3d-units-handler.ts
libraries/bio/src/molecule-3d/types.ts
libraries/bio/src/molecule/molecule-build-data.ts
libraries/bio/src/molecule/molecule-units-handler.ts
libraries/bio/src/molecule/types.ts
libraries/bio/src/monomer-works/monomer-utils.ts
libraries/bio/src/utils/units-handler-base.ts
libraries/bio/src/utils/units-handler.ts
libraries/bio/src/viewers/biotrack.ts
libraries/bio/src/viewers/molecule3d.ts
libraries/bio/src/viewers/molstar-viewer.ts
libraries/bio/src/viewers/ngl-gl-viewer.ts
libraries/bio/src/viewers/vd-regions.ts
libraries/bio/src/viewers/web-logo.ts

Add Molecule3DUnitsHandler
Default value for pdbTag prop of Biostructure

#2481: BsV: Import ligands from pdbqt format

---

packages/Chem/src/rendering/rdkit-cell-renderer.ts

@MariaDolotova This is about the discussion we had about #2529 and #2493 - how to satisfy all alignment/highlighting use cases without triggering unexpected behavior.
I think this PR should fix things for both of us - please let me know if this is not the case.

Differentiate between own and rebuilt coordinates

---

libraries/utils/package-lock.json
libraries/utils/package.json
libraries/utils/src/test.ts

utils: Fix testEvent to unsubscribe event and timer
utils: Fix testViewer to report errors on getOptions, getProperties

#2492: BsV: AutoDock, display results in grid, lib bio

---

packages/Bio/package-lock.json
packages/Bio/package.json
packages/Bio/src/package-types.ts
packages/Bio/src/utils/get-region-func-editor.ts

#2492: BsV: AutoDock, display results in grid, Bio

---

packages/ODEs/CHANGELOG.md
packages/ODEs/README.md
packages/ODEs/detectors.js
packages/ODEs/package-lock.json
packages/ODEs/package.json
packages/ODEs/src/app.ts
packages/ODEs/src/constants.ts
packages/ODEs/src/package.ts
packages/ODEs/src/scripting-tools.ts
packages/ODEs/src/templates.ts
packages/ODEs/src/ui-constants.ts

Solver is modified to Diff Studio. UI & UX features are changed.

GROK-14379: ODEs: Improve UI/UX

---

packages/ODEs/CHANGELOG.md
packages/ODEs/package-lock.json
packages/ODEs/package.json
packages/ODEs/src/app.ts
packages/ODEs/src/scripting-tools.ts
packages/ODEs/src/ui-constants.ts

Solver package name fix and run on start feature

GROK-14432: ODEs: Minor fixes

---

packages/SimPKPD/CHANGELOG.md
packages/SimPKPD/package-lock.json
packages/SimPKPD/package.json
packages/SimPKPD/src/package.ts
packages/SimPKPD/wasm/help-panel.js

String input bug in the demo app is fixed

GROK-14503: SimPKPD | Demo app: String input bug fix

---

packages/EDA/CHANGELOG.md
packages/EDA/README.md
packages/EDA/package-lock.json
packages/EDA/package.json
packages/EDA/src/missing-values-imputation/knn-imputer.ts
packages/EDA/src/missing-values-imputation/ui-constants.ts
packages/EDA/src/missing-values-imputation/ui.ts
packages/EDA/src/package.ts

Add missing values imputation by the kNN method

GROK-14366: EDA: Missing values imputation

---

packages/Bioreactors/CHANGELOG.md
packages/Bioreactors/package-lock.json
packages/Bioreactors/package.json
packages/Bioreactors/src/package.ts
packages/Bioreactors/wasm/helpPanel.js
packages/SimPKPD/CHANGELOG.md
packages/SimPKPD/package-lock.json
packages/SimPKPD/package.json
packages/SimPKPD/src/package.ts

In the Bioreactor & SimPKPD packages, annotations of functions are updated

GROK-14702: Bioreactor & SimPKPD: Annotations update

---

libraries/compute-utils/function-views/src/sensitivity-analysis-view.ts
libraries/compute-utils/function-views/src/variance-based-analysis/random-sensitivity-analysis.ts
libraries/compute-utils/function-views/src/variance-based-analysis/sa-outputs-routine.ts
libraries/compute-utils/function-views/src/variance-based-analysis/sobol-sensitivity-analysis.ts

Fixed column names issue (non-unique case)

GROK-14701: Sens Analysis: Column names issue fix

---

packages/EDA/CHANGELOG.md
packages/EDA/package-lock.json
packages/EDA/package.json
packages/EDA/src/eda-ui.ts
packages/EDA/src/package.ts

Processing of tables form a local file using PCA, PLS is fixed

GROK-13921: EDA | PCA, PLS: Fix processing local files

---

packages/Bio/scripts/sequence_generator.md
packages/Bio/scripts/sequence_generator.py

Rework of the sequence generator script.
- Ability to generate multiple activity columns with correlated activities
- More user-friendly generation options
- Code refactoring

GitHub-2676: Sequence generator multi activities

---

packages/Bioreactors/CHANGELOG.md
packages/Bioreactors/package-lock.json
packages/Bioreactors/package.json
packages/Bioreactors/src/package.ts

Update annotations for better UX

GROK-15012: Bioreactor: Annotations upd

---

packages/Compute/CHANGELOG.md
packages/Compute/package-lock.json
packages/Compute/package.json

Updated version with respect to compute-utils Sensitivity Analsysis updates

GROK-14701: Compute | SA: Update version

---

packages/ODEs/CHANGELOG.md
packages/ODEs/README.md
packages/ODEs/files/bioreactor.ivp
packages/ODEs/package-lock.json
packages/ODEs/package.json
packages/ODEs/src/app.ts
packages/ODEs/src/ui-constants.ts
packages/ODEs/src/use-cases.ts

GROK-15112: Diff Studio: Bioreactor example

---

libraries/compute-utils/CHANGELOG.md
libraries/compute-utils/function-views/index.ts
libraries/compute-utils/function-views/src/sensitivity-analysis-view.ts
libraries/compute-utils/index.ts
libraries/compute-utils/package-lock.json
libraries/compute-utils/package.json

Sensitivity Analysis input form styles fixes

ComputeUtils: Sens Analysis styles

---

packages/Compute/CHANGELOG.md
packages/Compute/package-lock.json
packages/Compute/package.json

SA input form styles are fixed

Compute: Sens Analysis styles fix

---

packages/ODEs/CHANGELOG.md
packages/ODEs/README.md
packages/ODEs/files/advanced.ivp
packages/ODEs/files/bioreactor.ivp
packages/ODEs/files/chem-react.ivp
packages/ODEs/files/extended.ivp
packages/ODEs/files/fermentation.ivp
packages/ODEs/files/ga-production.ivp
packages/ODEs/files/nimotuzumab.ivp
packages/ODEs/files/pk-pd.ivp
packages/ODEs/files/robertson.ivp
packages/ODEs/package-lock.json
packages/ODEs/package.json
packages/ODEs/src/app.ts
packages/ODEs/src/scripting-tools.ts
packages/ODEs/src/templates.ts
packages/ODEs/src/ui-constants.ts
packages/ODEs/src/use-cases.ts
packages/ODEs/tsconfig.json
packages/ODEs/webpack.config.js

Implemented:
- E-notation use
- direct call of Sensitivity Analysis
- extended checks of model correctness

GROK-15116: Diff Studio: UI/UX improvement

---

packages/ODEs/CHANGELOG.md
packages/ODEs/package-lock.json
packages/ODEs/package.json
packages/ODEs/src/scripting-tools.ts
packages/ODEs/tsconfig.json

Added sidebar annotation to generated JS-scripts

GROK-15294: Diff Studio: Sidebar feature

---

packages/NLP/CHANGELOG.md
packages/NLP/package-lock.json
packages/NLP/package.json
packages/NLP/src/stemming-tools/stemming-tools.ts

Fixed multiple filters creating in stemming-based search (SBS)

GROK-15345: NLP | SBS: Fix filters

---

packages/SimPKPD/CHANGELOG.md
packages/SimPKPD/package-lock.json
packages/SimPKPD/package.json
packages/SimPKPD/src/package.ts

Added the fitting feature, updated min/max-s

GROK-15581: SimPKPD: Fitting feature

---

packages/Compute/CHANGELOG.md
packages/Compute/package-lock.json
packages/Compute/package.json

Updated version with respect to the changes in compute-utils

GROK-15320: Compute: Bump version

---

libraries/compute-utils/CHANGELOG.md
libraries/compute-utils/function-views/src/fitting-view.ts
libraries/compute-utils/function-views/src/sensitivity-analysis-view.ts
libraries/compute-utils/package-lock.json
libraries/compute-utils/package.json

GROK-15720: Compute: Fix imports

---

packages/Compute/CHANGELOG.md
packages/Compute/package-lock.json
packages/Compute/package.json

Bumped version due to the changes in the compute-utils lib

GROK-15720: Compute: Bump ver

---

packages/Bioreactors/CHANGELOG.md
packages/Bioreactors/package-lock.json
packages/Bioreactors/package.json
packages/Bioreactors/src/package.ts

GROK-16404: Bioreactor: Demo app

---

packages/SimPKPD/CHANGELOG.md
packages/SimPKPD/package-lock.json
packages/SimPKPD/package.json
packages/SimPKPD/src/package.ts

GROK-14353: SimPKPD: Demo app

---

libraries/compute-utils/shared-components/src/history-list.ts

GROK-16240: ColumnMetaHelper: Replaced tags usages with ColumnMetaHelper

---

packages/UsageAnalysis/files/Test Track/Browse/Japanese in MyFiles.md
packages/UsageAnalysis/files/Test Track/Browse/Local deploy.md
packages/UsageAnalysis/files/Test Track/Browse/Package manager.md
packages/UsageAnalysis/files/Test Track/Closed tickets/Tickets.md
packages/UsageAnalysis/files/Test Track/Connections/External Provider.md
packages/UsageAnalysis/files/Test Track/DiffStudio/Cyclic models.md
packages/UsageAnalysis/files/Test Track/DiffStudio/Fitting.md
packages/UsageAnalysis/files/Test Track/DiffStudio/Open model.md
packages/UsageAnalysis/files/Test Track/DiffStudio/Scripting.md
packages/UsageAnalysis/files/Test Track/DiffStudio/Sensitivity Analysis.md
packages/UsageAnalysis/files/Test Track/DiffStudio/Stages.md
packages/UsageAnalysis/files/Test Track/EDA/ML methods/Linear Regression.md
packages/UsageAnalysis/files/Test Track/EDA/ML methods/PLS Regression.md
packages/UsageAnalysis/files/Test Track/EDA/ML methods/Softmax.md
packages/UsageAnalysis/files/Test Track/EDA/ML methods/XGBoost1.md
packages/UsageAnalysis/files/Test Track/EDA/ML methods/XGBoost2.md
packages/UsageAnalysis/files/Test Track/EDA/Multivariate Analysis.md
packages/UsageAnalysis/files/Test Track/EDA/PCA.md
packages/UsageAnalysis/files/Test Track/EDA/PLS.md
packages/UsageAnalysis/files/Test Track/Tooltips/Line chart - aggregated tooltip.md
packages/UsageAnalysis/files/Test Track/Viewers/Bar chart.md
packages/UsageAnalysis/files/Test Track/Viewers/Filter panel/Tasks.md
packages/UsageAnalysis/files/Test Track/Viewers/Grid.md
packages/UsageAnalysis/files/Test Track/Viewers/Line chart.md
packages/UsageAnalysis/files/Test Track/Viewers/Scatter plot.md
packages/UsageAnalysis/files/Test Track/Viewers/Trellis plot.md

manual test updates for Diff Studio, EDA, Added tests for closed NX tickets, and more...

ua: test track: manual test updates

---

packages/ODEs/CHANGELOG.md
packages/ODEs/package-lock.json
packages/ODEs/package.json

ODEs: Fix dependencies

---

libraries/compute-utils/CHANGELOG.md
libraries/compute-utils/function-views/src/fitting-view.ts
libraries/compute-utils/package-lock.json
libraries/compute-utils/package.json

Fixed table input in the Fitting view

GROK-16642: Compute: Fixed fitting

---

packages/Compute/CHANGELOG.md
packages/Compute/package-lock.json
packages/Compute/package.json

Bumped version due fixing df input bug in the compute-utils lib

GROK-16642: Compute: Bumped version

---

packages/ODEs/CHANGELOG.md
packages/ODEs/README.md
packages/ODEs/files/examples/pk-pd.ivp
packages/ODEs/files/examples/pk.ivp
packages/ODEs/package-lock.json
packages/ODEs/package.json
packages/ODEs/src/app.ts
packages/ODEs/src/demo-models.ts
packages/ODEs/src/ui-constants.ts
packages/ODEs/src/use-cases.ts

- Added the use of lookup tables in the Sensitivity Analysis & Fitting features
- Updated demos, fixed typos & links

GROK-16748: Diff Studio: Lookup tables in SA & Fitting

---

packages/PowerGrid/src/webgpu/scatterplot.ts

Now selection will be drawn as an overlay for WebGPU rendering.
Fixed single shape drawing to be correct.

GROK-16923: Improve selection drawing step

---

packages/EDA/CHANGELOG.md
packages/EDA/package-lock.json
packages/EDA/package.json
packages/EDA/src/pls/pls-tools.ts

GROK-16974: EDA: Fixed MVA

---

help/explore/missing-values-imputation.md

Added descirption of the KNN method

GROK-19674: Help: KNN imputer upd

---

packages/DiffStudio/CHANGELOG.md
packages/DiffStudio/package-lock.json
packages/DiffStudio/package.json
packages/DiffStudio/src/constants.ts
packages/DiffStudio/src/package.ts
packages/DiffStudio/src/scripting-tools.ts

* Updated computations the loop & update features
* Added the platform function for solving equations

GROK-16938 Diff Studio: Computations upd, platform funcs

---

packages/DiffStudio/CHANGELOG.md
packages/DiffStudio/README.md
packages/DiffStudio/package-lock.json
packages/DiffStudio/package.json
packages/DiffStudio/src/app.ts
packages/DiffStudio/src/utils.ts

Fixed open menu bug. Updated readme

GROK-17553: Diff Studio: Fixed open menu

---

packages/EDA/CHANGELOG.md
packages/EDA/package-lock.json
packages/EDA/package.json
packages/EDA/src/pls/pls-tools.ts
packages/EDA/src/utils.ts

Updated the Multivariate Analysis demo

GROK-17602: EDA: MVA demo upd

---

packages/Compute/CHANGELOG.md
packages/Compute/package-lock.json
packages/Compute/package.json

Updated compute-utils: in webworkers parameter optimization for Diff Studio models

GROK-17560: Compute: Compute utils upd

---

libraries/compute-utils/CHANGELOG.md
libraries/compute-utils/function-views/src/fitting-view.ts
libraries/compute-utils/function-views/src/fitting/diff-studio/defs.ts
libraries/compute-utils/function-views/src/fitting/diff-studio/fitting-utils.ts
libraries/compute-utils/function-views/src/fitting/diff-studio/nelder-mead.ts
libraries/compute-utils/function-views/src/fitting/diff-studio/workers/basic.ts
libraries/compute-utils/package-lock.json
libraries/compute-utils/package.json

Implemented the use of pipelines for fitting diff studio models

GROK-17452: Fitting view: Pipelines

---

libraries/compute-utils/CHANGELOG.md
libraries/compute-utils/function-views/src/fitting/diff-studio/fitting-utils.ts
libraries/compute-utils/function-views/src/fitting/diff-studio/nelder-mead.ts
libraries/compute-utils/package-lock.json
libraries/compute-utils/package.json

Fixed input vector computation for complex models

GROK-17560: Compute-utils: Fitting view

---

packages/Tutorials/package-lock.json
packages/Tutorials/src/tracks/compute/tutorials/diff-equations-tutorial.ts
packages/Tutorials/src/tracks/compute/tutorials/fitting-tutorial.ts
packages/Tutorials/src/tracks/compute/tutorials/sensitivity-analysis-tutorial.ts
packages/Tutorials/src/tracks/compute/tutorials/utils.ts

Fixed tutorials with respect to Browse UX updates:
- Diff Studio
- Fitting
- Sens. Analysis

GROK-17690: Tutorials: Sci computing

---

packages/EDA/package-lock.json
packages/EDA/package.json
packages/EDA/src/pls/pls-tools.ts

Updated Multivariate analysis with respect to Browse UX changes

GROK-17740: EDA: MVA

---

packages/DiffStudio/CHANGELOG.md
packages/DiffStudio/README.md
packages/DiffStudio/files/library/bioreactor.ivp
packages/DiffStudio/files/library/chem-react.ivp
packages/DiffStudio/files/library/energy-n-control.ivp
packages/DiffStudio/files/library/fermentation.ivp
packages/DiffStudio/files/library/ga-production.ivp
packages/DiffStudio/files/library/nimotuzumab.ivp
packages/DiffStudio/files/library/pk-pd.ivp
packages/DiffStudio/files/library/pk.ivp
packages/DiffStudio/files/library/pollution.ivp
packages/DiffStudio/files/library/robertson.ivp
packages/DiffStudio/files/templates/extended.ivp
packages/DiffStudio/package-lock.json
packages/DiffStudio/package.json
packages/DiffStudio/src/app.ts
packages/DiffStudio/src/demo/bioreactor.ts
packages/DiffStudio/src/templates.ts
packages/DiffStudio/src/ui-constants.ts
packages/DiffStudio/src/use-cases.ts

- Replaced Model Catalog with Model Hub
- Removed tags

GROK-17920: Diff Studio: Model Hub

---

help/compute/diff-studio.md
help/compute/models.md

Fixed links to the example models

GROK-17946: Help: Diff Studio: Fixed links

---

packages/Tutorials/CHANGELOG.md
packages/Tutorials/package-lock.json
packages/Tutorials/package.json
packages/Tutorials/src/tracks/compute/tutorials/diff-equations-tutorial.ts
packages/Tutorials/src/tracks/compute/tutorials/fitting-tutorial.ts
packages/Tutorials/src/tracks/compute/tutorials/sensitivity-analysis-tutorial.ts
packages/Tutorials/src/tracks/compute/tutorials/utils.ts

Fix elements in the Parameters Optimization tutorial

GROK-17976: Tutorials: Fitting

---

packages/DiffStudio/CHANGELOG.md
packages/DiffStudio/package-lock.json
packages/DiffStudio/package.json
packages/DiffStudio/src/app.ts

Improved input values precision when using lookup tables

GROK-17998: Diff Studio: Inputs precision

---

libraries/compute-utils/CHANGELOG.md
libraries/compute-utils/function-views/css/fitting-view.css
libraries/compute-utils/function-views/src/fitting-view.ts
libraries/compute-utils/function-views/src/fitting/constants.ts
libraries/compute-utils/function-views/src/fitting/diff-studio/nelder-mead.ts
libraries/compute-utils/function-views/src/fitting/fitting-utils.ts
libraries/compute-utils/function-views/src/fitting/optimizer.ts
libraries/compute-utils/function-views/src/fitting/scalars-fit-radar.ts
libraries/compute-utils/package-lock.json
libraries/compute-utils/package.json

Updated the Fitting feature:
- target columns selection
- fitting results displaying
- goodness of fit viewers creation

GROK-17991: Fitting: Updated UX and results displaying

---

packages/Compute/CHANGELOG.md
packages/Compute/package-lock.json
packages/Compute/package.json

Updated version of the compute utils

GROK-17991: Compute: Fitting update

---

packages/Compute2/CHANGELOG.md
packages/Compute2/package-lock.json
packages/Compute2/package.json

Updated compute utils with fitting modifications

GROK-17991: Compute2: Compute utils update

---

packages/DiffStudio/CHANGELOG.md
packages/DiffStudio/package-lock.json
packages/DiffStudio/package.json

Updated the fitting feature from compute utils

GROK-17991: Diff Studio: Fitting upd

---

packages/EDA/CHANGELOG.md
packages/EDA/package-lock.json
packages/EDA/package.json
packages/EDA/src/package.ts
packages/EDA/src/pls/pls-constants.ts
packages/EDA/src/pls/pls-ml.ts
packages/EDA/src/pls/pls-tools.ts
packages/EDA/src/regression.ts
packages/EDA/src/tests/linear-methods-tests.ts

- Implemented the Quadratic PLS regression
- Improved MVA and PLS UI UX

GROK-18034: EDA: Quadratic PLS

---

packages/Tutorials/CHANGELOG.md
packages/Tutorials/package-lock.json
packages/Tutorials/package.json
packages/Tutorials/src/tracks/ml/tutorials/multivariate-analysis.ts

Updated UI in the multivariate analysis tutorial

GROK-18034: Tutorials: MVA

---

.github/workflows/python-api.yml
libraries/compute-utils/CHANGELOG.md
libraries/compute-utils/function-views/src/sensitivity-analysis-view.ts
libraries/compute-utils/function-views/src/variance-based-analysis/constants.ts
libraries/compute-utils/function-views/src/variance-based-analysis/diff-studio/defs.ts
libraries/compute-utils/function-views/src/variance-based-analysis/diff-studio/model-evaluator.ts
libraries/compute-utils/function-views/src/variance-based-analysis/diff-studio/sens-analysis-utils.ts
libraries/compute-utils/function-views/src/variance-based-analysis/diff-studio/workers/analysis.ts
libraries/compute-utils/function-views/src/variance-based-analysis/grid-sensitivity-analysis.ts
libraries/compute-utils/function-views/src/variance-based-analysis/input-tools.ts
libraries/compute-utils/function-views/src/variance-based-analysis/random-sensitivity-analysis.ts
libraries/compute-utils/function-views/src/variance-based-analysis/sa-outputs-routine.ts
libraries/compute-utils/function-views/src/variance-based-analysis/sobol-sensitivity-analysis.ts
libraries/compute-utils/function-views/src/variance-based-analysis/utils.ts
libraries/compute-utils/package.json
packages/DiffStudio/src/app.ts

Implemented sensitivity analysis in workers for Diff Studio based models

GROK-17888: Sens Analysis: In workers computations

---

packages/DiffStudio/CHANGELOG.md
packages/DiffStudio/package-lock.json
packages/DiffStudio/package.json
packages/DiffStudio/src/app.ts
packages/DiffStudio/src/demo/pk-pd.ts

Implemented sensitivity analysis in webworkers

GROK-17888: Diff Studio: Sens analysis upd

---

packages/Compute2/CHANGELOG.md
packages/Compute2/package-lock.json
packages/Compute2/package.json

Updated compute utils with sens analysis modifications

GROK-17888: Compute2: Compute utils update

---

packages/DiffStudio/CHANGELOG.md
packages/DiffStudio/package-lock.json
packages/DiffStudio/package.json
packages/DiffStudio/src/package.g.ts

Bumped the package version due to js api update

GROK-18431: Diff Studio: JS API version upd

---

packages/EDA/CHANGELOG.md
packages/EDA/package-lock.json
packages/EDA/package.json
packages/EDA/src/package-api.ts
packages/EDA/src/package.g.ts
packages/EDA/src/package.ts

Improved the usability of the PCA dialog

GROK-18781: EDA: PCA dialog update
