datagrok-ai/public

- packages/Chem/src/rdkit_cell_renderer.js
- packages/Chem/src/rdkit_substruct_library.js
- if `RdKitSubstructLibrary.search()` is passed an invalid query, return no matches rather than crashing
Currently if `get_mol` throws an exception inside `RdKitSubstructLibrary.search()`, an uncaught exception in Promise will be raised, causing the UI to hang
- the renderer should not attempt to call `is_valid()` on a `null` mol
in `_fetchMolGetOrCreate` the first `try..catch` block can set mol to `null`, so calling `mol.is_valid()` is bound to throw an exception, which in turn causes unnecessary verbose logging in the console
- the renderer should check if `rdkitScaffoldMol` is not `null` and valid before passing it to `generate_aligned_coords()`
to avoid throwing unnecessary exceptions
same as above - avoid unnecessary logging that clutters the console
- mols which are invalid should …
> Avoid that RdKitSubstructLibrary crashes on invalid mols and a few other clean-ups

- packages/Peptides/src/package.ts
- packages/Peptides/src/peptide-sar-viewer/molecular_measure.ts
#93
1. Added molecular weight calculation for a peptide sequence.
2. Added scatter plot size from the calculated molecular weights.
Works only for sequences with natural residues.
> Peptides: Molecular weights calculation for peptide space scatter plot

- js-api/src/entities.ts
Current `object` type forces to use `@ts-ignore` in all places the `getCredentials` is used. Since `object` type has no own props, any access to `getCredentials().parameters` raises compilation error. 
The canonical way to get param (`getCredentials().parameters[%paramName%]`) is ideally described by `Record<string, string>` type.
> Changed getCredentials().parameters return type to Record

- packages/Chem/src/rdkit-api.ts
- packages/Chem/src/rendering/rdkit-cell-renderer.ts
Integrates #554.
Make sure the molecule has coordinates before calling `normalize_depiction()` and `straighten_depiction()`
> Integrates #554

- packages/Bio/package.json
Fix Bio package default share allowing canView for All users
> GROK-12136: Bio | Stability: Fix Bio default share

- packages/Bio/detectors.js
- packages/Bio/package.json
- packages/Bio/src/package.ts
- packages/Bio/src/tests/detectors-tests.ts
- packages/Bio/src/tests/similarity-diversity-tests.ts
- packages/Bio/tsconfig.json
- packages/Bio/webpack.config.js
The detectMacromolecule is too aggressive.
The Detector will not recognize the notation ‘fasta’ with the alphabet 'UN' non-multichar, because words of the natural language are too similar to oligomers (notation fasta with alphabet UN non-multichar).
Tests for detectMacromolecule require a fix to test all available non-positive columns for false positive results.
Enable the use of required column name parts.
> atanas/GROK-12547: Bio: fix detect macromolecule and tests

- packages/ApiTests/src/package-test.ts
- packages/ApiTests/src/package.ts
- packages/ApiTests/src/viewers/filters.ts
- packages/ApiTests/src/viewers/test-custom-filter.ts
There was a problem to display the custom PTM filter in MLB.
The problem was solved by specifying a column name to associate the custom filter with, though the PTM filter works on data of multiple columns.
Tests for the ApiTests package have been created to test displaying custom filters, they also are examples showing how to use custom filters.
> GROK-12450: Viewers | Filters: Custom filter test

- packages/Dendrogram/package.json
- packages/Dendrogram/src/viewers/dendrogram.ts
- packages/Dendrogram/src/viewers/tree-renderers/canvas-tree-renderer.ts
Add context menu option to dendrogram for resetting the view back to default (after moving around and zooming).
Same reset happens when user double-clicks on 'white space'
> GROK-12827: Dendrogram: Add option to reset view

- packages/Chem/src/rdkit_lib_version.js
- packages/Chem/src/utils/chem-common-rdkit.ts
This update brings two improvements:
- query bonds are now depicted in black rather than in grey `#7F7F7F`
- molecules bearing no substituents at positions where the scaffold bears a query atom including a H now are correctly aligned as expected, while previously they were not
> update MinimalLib to version 1.2.3

- packages/Bio/detectors.js
- packages/Bio/package.json
- packages/Bio/src/package.ts
Fix detectMacromolecule to recognize protein alphabet dataset rejected as SMARTS.
Adjust decoy cutoff for SMARTS
Adjust decoy cutoff for likely columns
> GROK-12136: Bio | Tools: Fix detectMacromolecule

- libraries/chem-meta/src/rdkit-api.ts
- packages/Chem/src/rendering/rdkit-cell-renderer.ts
- packages/Chem/src/utils/chem-common-rdkit.ts
- packages/Chem/src/utils/mol-creation_rdkit.ts
This PR fixes a regression that I have just noticed (i.e., fonts getting noticeably larger when molecules are aligned to a scaffold) caused by the fact that `JSMol.has_coords()` does not return a `boolean` anymore, but a `number`, so code needs to be updated accordingly in a few places.
makes the highlighting halo around scaffold atoms a bit thicker and a bit lighter to improve visibility.
@StLeonidas @MariaDolotova this is an important one; could you please it is merged into `Chem` ASAP? Many thanks in advance.
> Fix has coords regression

- tools/bin/commands/help.ts
- tools/bin/commands/test.ts
- tools/bin/utils/test-utils.ts
- tools/package-lock.json
- tools/package.json
1. Added flags `--catchUnhandled` and `--report`
2. Upgraded `puppeteer` version from `^13.7.0` to `^20.3.0` (latest). The old version had been chosen when testing was done via `jest` (we had fixed lib versions).
3. Switched to `headless: 'new'` https://developer.chrome.com/articles/new-headless/ (shouldn't affect any of our working environments)
> GROK-13133 Tools: Ability to report failed package tests to audit

- libraries/tutorials/src/tutorial.ts
- packages/Tutorials/css/tutorial.css
Use the `ui.hints` methods to place interative hints instead of the custom methods (resolves styles incompatibility issues).
> Tutorials: Switch to UI hints

- js-api/src/functions.ts
Checked typing by compiling `compute-utils` and `ApiTests`
> JS API: Fixed FuncCall params typing

- libraries/chem-meta/src/rdkit-api.ts
- packages/Chem/src/rdkit-service/rdkit-service-worker-substructure.ts
- packages/Chem/src/rendering/rdkit-cell-renderer.ts
- packages/Chem/src/widgets/scaffold-tree.ts
The `Chem` package is currently broken as the `1.2.8` version of MinimalLib features this API change compared to the previous version.
@MariaDolotova @StLeonidas Could you please apply this fix ASAP to avoid building a broken `Chem` package?
Thanks in advance!
> rename set_aromatic_form to convert_to_aromatic_form

- README.md
This PR changes "JavaScript development" href to a valid one.
> Update README.md: fix 'JavaScript development' URL

- packages/Chem/src/rdkit_lib_version.js
@MariaDolotova This PR includes updated MinimalLib to 1.2.11 including log capture functionality and the fix for [#6640]((https://github.com/rdkit/rdkit/issues/6640). This reverts the temporary workaround I had put in and includes the proper fix.
> Updated MinimalLib to 1.2.11

- help/develop/help-pages/github-workflow.mdx
Reorganized the Helop docs contribution pages.
- Moved installation instructions to a separate section
- Added links to GitHub policy for commit and branch naming
> GROK-13754: Help docs github workflow: Reorganized and improved

- packages/Chem/src/rendering/rdkit-cell-renderer.ts
@MariaDolotova @StLeonidas
This PR fixes a major regression that caused **ALL** molecules rendered from SMILES to have no stereochemistry.
Molecules were being tested for the presence of pre-existing 2D coordinates _after_ coordinates had been generated, so the check was always true.
> Fixes major regression in SMILES stereochemistry depiction

- packages/EDA/CHANGELOG.md
- packages/EDA/package.json
- packages/EDA/src/package.ts
The method is moved to top-menu ML | Analyze and renamed to just _ANOVA_ instead _Analysis of variances (ANOVA)_.
> GROK-14124: EDA | ANOVA: Naming upd

- packages/Chem/src/widgets/scaffold-tree.ts
@MariaDolotova @StLeonidas This small PR is to normalize the scale of scaffolds retrieved from the sketcher, such that their bond length is the same that RDKit expects. This avoids downstream issues such as:
1. heteroatom fonts being too large compared to the size of the scaffold
2. possible distortions upon attempting to align molecules to such scaffolds
For instance, fonts that previously looked like this
are now properly scaled:
> fix(DDIS-6462): Fonts are too large compared to the scaffold size

- libraries/bio/package-lock.json
- libraries/bio/package.json
- libraries/bio/src/utils/composition-table.ts
- libraries/bio/src/utils/sequence-position-scroller.ts
- packages/Bio/src/viewers/web-logo-viewer.ts
- packages/Bio/src/widgets/composition-analysis-widget.ts
- packages/Bio/src/widgets/sequence-scrolling-widget.ts
Moved `buildCompositionTable` out of `packages/Bio/.../composition-analysis-widget` to `libraries/bio/utils/composition-table`. 
- Note, i left `getCompositionAnalysisWidget` in that same file. Is that right?
Also bumped the library's `package.json` version as @drizhina showed on a call for it to be gh-action propagated to npm. Hopefully got that right as well?
> Moved composition-table to library, bump bio

- packages/Bio/src/widgets/sequence-scrolling-widget.ts
- packages/BiostructureViewer/.eslintrc.json
- packages/BiostructureViewer/src/package-api.ts
- packages/BiostructureViewer/src/package.ts
- packages/BiostructureViewer/src/pdb-entry.ts
- packages/BiostructureViewer/src/utils/pdb-grid-cell-renderer.ts
- packages/BiostructureViewer/src/utils/rcsb-gql-adapter.ts
- packages/BiostructureViewer/src/utils/sequence-handler.ts
- sequence extraction based on the PDB_ID value, column selectable via Bio>Transform>Fetch sequences from PDB...
- Added RCSB Gql "adapter" which now has only polyme bindings to fetch only those entities and nothing else, but can be extended to arbitrary fields in an pdb-x/mmcif file where structural bio tasks are concerned.
- slightly changed the logic which determines when `[sequence-scrolling-widget.ts]` renders (i think we missed an MSA check so it used to still render for just `SEQ`) which was no bueno in this case.
> BioStructure Viewer: sequence extraction based on the PDB_ID value
